# Vamos a realizar un analisis de reduccion de la dimensionalidad a traves del metodo TSNE en dos y tres dimensiones para encontrar patrones a partir de relaciones no lineales entre las variables debido a los bajos datos de correlacion que muestran las variables de uso en las ciudades seleccionadas.

In [16]:
from sklearn.manifold import TSNE

In [24]:
import pandas as pd

In [25]:
usos_wide = pd.read_csv("usos_wide.csv", sep = ',')
df_mm_usos_wide = pd.read_csv("ciudades_mm.csv")
df_st_usos_wide = pd.read_csv('ciudades_st.csv')

In [26]:
usos_wide.head()

,variable,ciudades,COM,ED_SING,EQUIP_EDU,EQUIP_OTR,EQUIP_SANI,HOS_REST,IND,IND_MX,OCIO_ESP,OFI,RES_PLU,RES_PLU_MX,RES_UNI,RES_UNI_MX,SIN_EDIF
0,Albacete_class.shp,Albacete,0.309544,4.775094,3.427693,4.188650,0.743391,0.408664,13.464698,6.489359,0.077490,0.384967,6.551059,5.127209,22.820463,0.788167,30.443552
1,Alcala_class.shp,Alcala,1.056955,7.641072,5.264190,6.815778,1.005046,0.463711,15.868683,12.523890,0.095006,1.287052,6.621817,2.875498,6.032543,0.313776,32.134984
2,Alcobendas_class.shp,Alcobendas,0.400440,5.448729,2.943100,5.116551,0.219057,0.200518,2.155552,4.377018,0.018557,2.453760,5.923401,1.340272,19.175420,1.588624,48.639002
3,Alcorcon_class.shp,Alcorcon,1.212290,4.340481,7.349396,11.821959,1.882375,0.182931,7.639873,8.182198,0.050832,0.217896,10.475900,4.596989,5.148168,0.131632,36.767081
4,Algeciras.shp,Algeciras.shp,0.580857,1.030783,2.160662,3.990147,0.597612,0.379388,5.176627,2.126968,0.055235,0.178552,3.154989,2.242866,25.815777,2.793453,49.716086

In [39]:
df_mm_usos_wide = df_mm_usos_wide.iloc[:,1:17]

In [42]:
df_st_usos_wide = df_st_usos_wide.iloc[:,1:17]

In [45]:
df_st_usos_wide.head()

,ciudades,COM,ED_SING,EQUIP_EDU,EQUIP_OTR,EQUIP_SANI,HOS_REST,IND,IND_MX,OCIO_ESP,OFI,RES_PLU,RES_PLU_MX,RES_UNI,RES_UNI_MX,SIN_EDIF
0,Albacete,0.309544,4.775094,3.427693,4.188650,0.743391,0.408664,13.464698,6.489359,0.077490,0.384967,6.551059,5.127209,22.820463,0.788167,30.443552
1,Alcala,1.056955,7.641072,5.264190,6.815778,1.005046,0.463711,15.868683,12.523890,0.095006,1.287052,6.621817,2.875498,6.032543,0.313776,32.134984
2,Alcobendas,0.400440,5.448729,2.943100,5.116551,0.219057,0.200518,2.155552,4.377018,0.018557,2.453760,5.923401,1.340272,19.175420,1.588624,48.639002
3,Alcorcon,1.212290,4.340481,7.349396,11.821959,1.882375,0.182931,7.639873,8.182198,0.050832,0.217896,10.475900,4.596989,5.148168,0.131632,36.767081
4,Algeciras.shp,0.580857,1.030783,2.160662,3.990147,0.597612,0.379388,5.176627,2.126968,0.055235,0.178552,3.154989,2.242866,25.815777,2.793453,49.716086

# De aqui en adelante vamos a realizar el TSNE. Interesante seria esta vez tratar de optimizar los parametros.

In [20]:
tsne = TSNE(n_components = 2, random_state = 42, n_iter = 5000)

In [21]:
df_st_usos_wide.iloc[:,1:16]

,ciudades,COM,ED_SING,EQUIP_EDU,EQUIP_OTR,EQUIP_SANI,HOS_REST,IND,IND_MX,OCIO_ESP,OFI,RES_PLU,RES_PLU_MX,RES_UNI,RES_UNI_MX
0,Albacete,0.309544,4.775094,3.427693,4.188650,0.743391,0.408664,13.464698,6.489359,0.077490,0.384967,6.551059,5.127209,22.820463,0.788167
1,Alcala,1.056955,7.641072,5.264190,6.815778,1.005046,0.463711,15.868683,12.523890,0.095006,1.287052,6.621817,2.875498,6.032543,0.313776
2,Alcobendas,0.400440,5.448729,2.943100,5.116551,0.219057,0.200518,2.155552,4.377018,0.018557,2.453760,5.923401,1.340272,19.175420,1.588624
3,Alcorcon,1.212290,4.340481,7.349396,11.821959,1.882375,0.182931,7.639873,8.182198,0.050832,0.217896,10.475900,4.596989,5.148168,0.131632
4,Algeciras.shp,0.580857,1.030783,2.160662,3.990147,0.597612,0.379388,5.176627,2.126968,0.055235,0.178552,3.154989,2.242866,25.815777,2.793453
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Valladolid,0.404746,4.732781,4.599511,8.504691,1.662326,0.406037,17.403132,8.563992,0.177049,0.335431,8.868738,5.696320,10.713216,0.915560
70,Vigo,0.276154,2.100296,4.802969,4.406184,0.538630,0.191656,5.991808,7.295622,0.167403,0.260198,0.791854,6.821427,5.153568,25.589182
71,Zamora,0.750087,2.970423,4.444969,9.497844,2.365705,0.215619,12.414006,6.331393,0.069630,0.133918,9.378723,5.071298,11.797034,1.704305
72,Zaragoza,0.477597,4.504671,3.232540,4.556002,1.013548,0.098948,12.834295,12.096169,0.093010,0.172093,7.585931,7.173644,8.182778,0.832779
73,doshermanas,0.604911,3.224782,2.930094,7.177283,0.414903,0.155636,11.281465,4.441596,0.012004,0.125410,2.236134,1.747948,23.431124,1.537872

In [22]:
usos_wide.iloc[:,2:17]

,COM,ED_SING,EQUIP_EDU,EQUIP_OTR,EQUIP_SANI,HOS_REST,IND,IND_MX,OCIO_ESP,OFI,RES_PLU,RES_PLU_MX,RES_UNI,RES_UNI_MX,SIN_EDIF
0,0.309544,4.775094,3.427693,4.188650,0.743391,0.408664,13.464698,6.489359,0.077490,0.384967,6.551059,5.127209,22.820463,0.788167,30.443552
1,1.056955,7.641072,5.264190,6.815778,1.005046,0.463711,15.868683,12.523890,0.095006,1.287052,6.621817,2.875498,6.032543,0.313776,32.134984
2,0.400440,5.448729,2.943100,5.116551,0.219057,0.200518,2.155552,4.377018,0.018557,2.453760,5.923401,1.340272,19.175420,1.588624,48.639002
3,1.212290,4.340481,7.349396,11.821959,1.882375,0.182931,7.639873,8.182198,0.050832,0.217896,10.475900,4.596989,5.148168,0.131632,36.767081
4,0.580857,1.030783,2.160662,3.990147,0.597612,0.379388,5.176627,2.126968,0.055235,0.178552,3.154989,2.242866,25.815777,2.793453,49.716086
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,0.404746,4.732781,4.599511,8.504691,1.662326,0.406037,17.403132,8.563992,0.177049,0.335431,8.868738,5.696320,10.713216,0.915560,27.016471
70,0.276154,2.100296,4.802969,4.406184,0.538630,0.191656,5.991808,7.295622,0.167403,0.260198,0.791854,6.821427,5.153568,25.589182,35.613050
71,0.750087,2.970423,4.444969,9.497844,2.365705,0.215619,12.414006,6.331393,0.069630,0.133918,9.378723,5.071298,11.797034,1.704305,32.855046
72,0.477597,4.504671,3.232540,4.556002,1.013548,0.098948,12.834295,12.096169,0.093010,0.172093,7.585931,7.173644,8.182778,0.832779,37.145995
73,0.604911,3.224782,2.930094,7.177283,0.414903,0.155636,11.281465,4.441596,0.012004,0.125410,2.236134,1.747948,23.431124,1.537872,40.678839

In [23]:
tsne_res_2d_df = tsne.fit_transform(usos_wide.iloc[:,2:17])
tsne_res_2d_mm = tsne.fit_transform(df_mm_usos_wide.iloc[:,1:16])
tsne_res_2d_st = tsne.fit_transform(df_st_usos_wide.iloc[:,1:16])

C:\Users\crist\miniconda3\envs\datamecum\lib\site-packages\sklearn\manifold\_t_sne.py:800: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
C:\Users\crist\miniconda3\envs\datamecum\lib\site-packages\sklearn\manifold\_t_sne.py:810: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(
C:\Users\crist\miniconda3\envs\datamecum\lib\site-packages\sklearn\manifold\_t_sne.py:800: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
C:\Users\crist\miniconda3\envs\datamecum\lib\site-packages\sklearn\manifold\_t_sne.py:810: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(

ValueError: could not convert string to float: 'Albacete'

In [ ]:
tsne_res_2d_df

In [ ]:
df_tsne = pd.DataFrame({'x':tsne_res_2d_df[:,0], 'y':tsne_res_2d_df[:,1]})
df_tsne_mm = pd.DataFrame({"x":tsne_res_2d_mm[:,0], "y":tsne_res_2d_mm[:,1]})
df_tsne_st = pd.DataFrame({"x":tsne_res_2d_st[:,0], "y":tsne_res_2d_st[:,1]})

In [ ]:
from sklearn.cluster import KMeans
from sklearn.cluster import AgglomerativeClustering

In [ ]:
usos_wide.loc[:,['ciudades', 'COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']].head(5)

In [ ]:
Ag_tsne = AgglomerativeClustering(n_clusters = 4)

Ag_tsne_df_cluster = Ag_tsne.fit(df_tsne.loc[:,['x','y']])
Ag_tsne_mm_cluster = Ag_tsne.fit(df_tsne_mm.loc[:,['x','y']])
Ag_tsne_st_cluster = Ag_tsne.fit(df_tsne_st.loc[:,['x','y']])

uso_wide_cluster = Ag_tsne.fit(usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

mm_usos_wide_cluster = Ag_tsne.fit(df_mm_usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

st_usos_wide_cluster = Ag_tsne.fit(df_st_usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

In [ ]:
uso_wide_cluster.labels_

In [ ]:
kmeans_tsne = KMeans(n_clusters = 4)
k_tsne_df = kmeans_tsne.fit(df_tsne.loc[:,['x','y']])
k_tsne_mm = kmeans_tsne.fit(df_tsne_mm.loc[:,["x","y"]])
k_tsne_st = kmeans_tsne.fit(df_tsne_st.loc[:,["x","y"]])

k_uso_wide_cluster = kmeans_tsne.fit(usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

k_mm_usos_wide_cluster = kmeans_tsne.fit(df_mm_usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

k_st_usos_wide_cluster = kmeans_tsne.fit(df_st_usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']])

In [ ]:
# Incorporar ciudades
df_tsne["ciudades"]  = df_mm_usos_wide.loc[:,"ciudades"]
df_tsne_mm["ciudades"] = df_mm_usos_wide.loc[:,"ciudades"]
df_tsne_st["ciudades"] = df_st_usos_wide.loc[:,"ciudades"]

## Incorporar cluster kmeans en dataframe tsne 
df_tsne['k_cluster'] = k_tsne_df.labels_
df_tsne_mm["kcluster_mm"] = k_tsne_mm.labels_
df_tsne_st["kcluster_st"] = k_tsne_st.labels_

## Incorporar clusters en hierarquical en dataframes tsne
df_tsne['hcluster_tsne'] = Ag_tsne_df_cluster.labels_
df_tsne_mm["hcluster_mm_tsne"] = Ag_tsne_mm_cluster.labels_
df_tsne_st["hcluster_st_tsne"] = Ag_tsne_st_cluster.labels_

# Incoporar kulster k means en base de datos df_mm_usos_wide
df_mm_usos_wide['kcluster'] = k_mm_usos_wide_cluster.labels_
df_st_usos_wide['kcluster'] = k_st_usos_wide_cluster.labels_

usos_wide['kcluster_or'] = k_uso_wide_cluster.labels_
usos_wide['kcluster_mm'] = k_mm_usos_wide_cluster.labels_ 
usos_wide['kcluster_st'] = k_st_usos_wide_cluster.labels_


usos_wide['hcluster_or'] = uso_wide_cluster.labels_
usos_wide['hcluster_mm'] = mm_usos_wide_cluster.labels_
usos_wide['hcluster_st'] = st_usos_wide_cluster.labels_

In [ ]:
# Agregamos algunas etiquetas al data original que provienen del TSNE

In [ ]:
usos_wide["kcluster_st_tsne"] = df_tsne_st["kcluster_st"]

In [ ]:
import seaborn as sn

In [ ]:
sn.scatterplot(data = df_tsne_mm, x = 'x', y = 'y', hue = "kcluster_mm", palette = "deep")

In [ ]:
## Disminuir el tamano de la letra

fig = go.Figure(data=go.Splom(
                  dimensions=[dict(label='COM', values=usos_wide['COM']),
                              dict(label='ED_SING', values=usos_wide['ED_SING']),
                              dict(label='EQUIP_EDU', values=usos_wide['EQUIP_EDU']),
                              dict(label='EQUIP_OTR', values=usos_wide['EQUIP_OTR']),
                              dict(label='EQUIP_SANI', values=usos_wide['EQUIP_SANI']),
                              dict(label='HOS_REST', values=usos_wide['HOS_REST']),
                              dict(label='IND', values=usos_wide['IND']),
                              dict(label='IND_MX', values=usos_wide['IND_MX']),
                              dict(label='OCIO_ESP', values=usos_wide['OCIO_ESP']),
                              dict(label='RES_PLU', values=usos_wide['RES_PLU']),
                              dict(label='RES_PLU_MX', values=usos_wide['RES_PLU_MX']),
                              dict(label='RES_UNI', values=usos_wide['RES_UNI']),
                              dict(label='RES_UNI_MX', values=usos_wide['RES_UNI_MX']),
                              dict(label='SIN_EDIF', values=usos_wide['SIN_EDIF'])],
                  text = df_mm_usos_wide['ciudades'],
                  marker=dict(color= usos_wide['Agcluster_mm'],
                              size=5,
                              showscale=False,
                              line=dict(width=0.5,
                                        color='rgb(230,230,230)')),
                  diagonal=dict(visible=False)))
                
        

fig.update_layout(title="Scatterplot matrix",
                  dragmode='select',
                  width=1000,
                  height=1000,
                  hovermode='closest')

fig.show()

In [ ]:
## Disminuir el tamano de la letra

fig = go.Figure(data=go.Splom(
                  dimensions=[dict(label='COM', values=usos_wide['COM']),
                              dict(label='ED_SING', values=usos_wide['ED_SING']),
                              dict(label='EQUIP_EDU', values=usos_wide['EQUIP_EDU']),
                              dict(label='EQUIP_OTR', values=usos_wide['EQUIP_OTR']),
                              dict(label='EQUIP_SANI', values=usos_wide['EQUIP_SANI']),
                              dict(label='HOS_REST', values=usos_wide['HOS_REST']),
                              dict(label='IND', values=usos_wide['IND']),
                              dict(label='IND_MX', values=usos_wide['IND_MX']),
                              dict(label='OCIO_ESP', values=usos_wide['OCIO_ESP']),
                              dict(label='RES_PLU', values=usos_wide['RES_PLU']),
                              dict(label='RES_PLU_MX', values=usos_wide['RES_PLU_MX']),
                              dict(label='RES_UNI', values=usos_wide['RES_UNI']),
                              dict(label='RES_UNI_MX', values=usos_wide['RES_UNI_MX']),
                              dict(label='SIN_EDIF', values=usos_wide['SIN_EDIF'])],
                  text = df_mm_usos_wide['ciudades'],
                  marker=dict(color= usos_wide['kcluster'],
                              size=5,
                              showscale=False,
                              line=dict(width=0.5,
                                        color='rgb(230,230,230)')),
                  diagonal=dict(visible=False)))
                
        

fig.update_layout(title="Scatterplot matrix",
                  dragmode='select',
                  width=1000,
                  height=1000,
                  hovermode='closest')

fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x= df_tsne['x'], y =df_tsne['y'], color=df_tsne['k_cluster'],
                 hover_data=[df_tsne['ciudades']])
fig.show()

In [ ]:
import plotly.express as px
fig = px.scatter(x= df_tsne_mm['x'], y =df_tsne_mm['y'], color=df_tsne_mm['kcluster_mm'],
                 hover_data=[df_tsne_mm['ciudades']])
fig.show()

In [ ]:
df_tsne_st

In [ ]:
import plotly.express as px
fig = px.scatter(x= df_tsne_st['x'], y =df_tsne_st['y'], color=df_tsne_st['kcluster_st'],
                 hover_data=[df_tsne_st['ciudades']])
fig.show()

In [ ]:
# Ahora vamos a ver el resultado de los cluster jerarquicos

In [ ]:
df_tsne

In [ ]:
fig = px.scatter(x= df_tsne['x'], y =df_tsne['y'], color=df_tsne['Agcluster'],
                 hover_data=[df_tsne_st['ciudades']])
fig.show()

In [ ]:
fig = px.scatter(x= df_tsne_mm['x'], y =df_tsne_mm['y'], color=df_tsne['Agcluster'],
                 hover_data=[df_tsne_mm['ciudades']])
fig.show()

In [ ]:
fig = px.scatter(x= df_tsne_st['x'], y =df_tsne_st['y'], color=df_tsne_st['Agcluster_st'],
                 hover_data=[df_tsne_st['ciudades']])
fig.show()

Los resultados anteriores pueden estar influido debido a que la escala de las dimensiones del TSNE no esta estandarizadas y por eso algunos patrones extranos. 

1.- Una opcion es volver a hacer los cluster estandarizando el TSNE. 
2.- Otra opcion es jugar con los parametros del TSNE para ver si podemos encontrar el mejor patron. 
3.- La tarcera opcion es volver hacerlo con 3 dimensiones.
4.- Volver a hacerlo después de descartar los outliers.

Podemos hacer un ensayo del árbol de decisión, sobre los del TSNE y las variables originales.

In [ ]:
1.- Primer aproximacion vamos a calcular el mejor cluster

In [ ]:
## Tenemos aquí que hacer el analisis de los grupos con group.by

df_st_usos_wide["cluster_st"] = df_tsne_st['Agcluster_st']

In [ ]:
1.- Vamos a realizar un arbol a partir de los valores de los cluster construidos a partir de los datos originales estandarizados.

2- Segundo arbol a partir de los clusters construidos a partir de los agrupamientos detectados por el TSN a partir de datos estandarizados.

In [ ]:
usos_wide["cluster_st_tsne"] = df_tsne_st['Agcluster_st']

In [ ]:
usos_wide.head(5)

In [ ]:
usos_wide.columns

In [ ]:
mean_cluster_TSNE_st  = usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR',
       'EQUIP_SANI', 'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU',
       'RES_PLU_MX', 'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF','cluster_st']].groupby(by = "cluster_st", axis = 0).mean()

In [ ]:
mean_cluster_TSNE_st

In [ ]:
mean_cluster_TSNE_st = mean_cluster_TSNE_st.reset_index()

In [ ]:
mean_cluster_TSNE_st.columns
variables = ['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR', 'EQUIP_SANI',
       'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU', 'RES_PLU_MX',
       'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']

In [ ]:
long_mean_cluster_TSNE_st = pd.melt(mean_cluster_TSNE_st, id_vars = "cluster_st", value_vars = variables )

In [ ]:
long_mean_cluster_TSNE_st

In [ ]:
import seaborn.objects as so
from seaborn import axes_style

In [ ]:
(
    so.Plot(long_mean_cluster_TSNE_st, x="USO", y="value", color = "cluster_st").theme({**axes_style("whitegrid"), "grid.linestyle": ":"})
    .add(so.Dot())
    .add(so.Line())
    .label(
        x = "  ",
        y = "Factor value"
    )
)

In [ ]:
fig = go.Figure(data=go.Splom(
                  dimensions=[dict(label='COM', values=usos_wide['COM']),
                              dict(label='ED_SING', values=usos_wide['ED_SING']),
                              dict(label='EQUIP_EDU', values=usos_wide['EQUIP_EDU']),
                              dict(label='EQUIP_OTR', values=usos_wide['EQUIP_OTR']),
                              dict(label='EQUIP_SANI', values=usos_wide['EQUIP_SANI']),
                              dict(label='HOS_REST', values=usos_wide['HOS_REST']),
                              dict(label='IND', values=usos_wide['IND']),
                              dict(label='IND_MX', values=usos_wide['IND_MX']),
                              dict(label='OCIO_ESP', values=usos_wide['OCIO_ESP']),
                              dict(label='RES_PLU', values=usos_wide['RES_PLU']),
                              dict(label='RES_PLU_MX', values=usos_wide['RES_PLU_MX']),
                              dict(label='RES_UNI', values=usos_wide['RES_UNI']),
                              dict(label='RES_UNI_MX', values=usos_wide['RES_UNI_MX']),
                              dict(label='SIN_EDIF', values=usos_wide['SIN_EDIF'])],
                  text = (usos_wide.loc[:,"ciudades"]),
                  marker=dict(color= usos_wide['cluster_mm'],
                              size=5,
                              showscale=False,
                              line=dict(width=0.5,
                                        color='rgb(230,230,230)')),
                  diagonal=dict(visible=False)))
                
        

fig.update_layout(title="Scatterplot matrix",
                  dragmode='select',
                  width=1000,
                  height=1000,
                  hovermode='closest')

fig.show()

In [ ]:
usos_wide.iloc[:,2:18]

In [ ]:
No es tan útil el gráfico anterior para ver patrones. Quizás sea más interesante un gráfico de barras paralelas.

In [ ]:
# Vamos a avanzar con el análisis de arbol de decision para explicar los grupos

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import ParameterGrid, GridSearchCV
from sklearn.metrics import make_scorer, accuracy_score, classification_report

In [ ]:
EPS = 10 * 6 # Esto que es? el umbral minimo?

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
usos_wide

In [ ]:
usos_wide.columns

In [ ]:
labels = usos_wide.Agcluster_st
labels_mm = usos_wide.Agcluster_mm
labels_tsne = usos_wide.cluster_st_tsne
features = usos_wide.loc[:,['COM', 'ED_SING', 'EQUIP_EDU', 'EQUIP_OTR', 'EQUIP_SANI',
       'HOS_REST', 'IND', 'IND_MX', 'OCIO_ESP', 'OFI', 'RES_PLU', 'RES_PLU_MX',
       'RES_UNI', 'RES_UNI_MX', 'SIN_EDIF']]

In [ ]:
full_tree = DecisionTreeClassifier(random_state=42)
full_tree_mm = DecisionTreeClassifier(random_state=42)
full_tree_tsne = DecisionTreeClassifier(random_state=42)
full_tree.fit(features, labels)
full_tree_mm.fit(features, labels_mm)
full_tree_tsne.fit(features, labels_tsne)

In [ ]:
feature_names = features.columns

In [ ]:
class_names = ["0","1","2","3",'4']

In [ ]:
plt.figure(figsize =(4,4), dpi =1000)
plot_tree(full_tree, feature_names = feature_names, class_names = class_names, filled = True)

In [ ]:
plt.figure(figsize =(4,4), dpi =1000)
plot_tree(full_tree_mm, feature_names = feature_names, class_names = class_names, filled = True)

In [ ]:
plt.figure(figsize =(4,4), dpi =1000)
plot_tree(full_tree_tsne, feature_names = feature_names, class_names = class_names, filled = True)

In [ ]:
print(classification_report(labels, full_tree.predict(features)))

In [ ]:
Importance = full_tree.feature_importances_

In [ ]:
pd.DataFrame({'features':feature_names, 'Importance':Importance})

1.- Si hago el cluster con los datos originales, luego ejecuto el arbol de decision puedo sacar una idea de la importancia relativa solo en base a los datos originales ##

2.- Esto lo puedo complementar nuevamente con un random forest, para tener la idea de muchos arboles. Sin embargo, no puedo ajustar los parametros en base a las predicciones si no tengo un conjunto de test.

In [ ]:
usos_wide['Agcluster']