Vamos a definir una funcion que nos permita leer los archivos de cada clase de metricas para cada municipio, y exportar el nuevo dataframe a un nuevo csv.

In [10]:
import pandas as pd
import os
import glob
import os
import string

# Funcion para leer los nombres de los archivos txt. La funcion tiene como argumento la ruta del directorio donde se encuentran los archivos

In [11]:
def leer_archivos(path):
    os.chdir(path)
    file_name = []
    for file in os.listdir():
        file_name.append(file)
    return (file_name)

In [16]:
ruta_forma = (r"C:\Users\CRISTIAN\github\clustering-metrics\datos\metricas\forma")

In [17]:
archivos_forma = leer_archivos(ruta_forma)

In [18]:
archivos_forma

['Albacete.txt',
 'Alcala.txt',
 'Alconbendas.txt',
 'Alcorcon.txt',
 'Algeciras.txt',
 'Alicante.txt',
 'Almeria.txt',
 'Avila.txt',
 'Badajoz.txt',
 'Badalona.txt',
 'Barcelona.txt',
 'Burgos.txt',
 'Caceres.txt',
 'Cadiz.txt',
 'Cartagena.txt',
 'Castello.txt',
 'Ceuta.txt',
 'Ciudad Real.txt',
 'Cordoba.txt',
 'Corunia.txt',
 'Cuenca.txt',
 'DosHermanas.txt',
 'Elche.txt',
 'Fuentelabra.txt',
 'Getafe.txt',
 'Gijon.txt',
 'Girona.txt',
 'Granada.txt',
 'Guadalajara.txt',
 'Hospitalet.txt',
 'Huelva.txt',
 'Huesca.txt',
 'Jaen.txt',
 'Jerez.txt',
 'Las Palmas.txt',
 'Leganes.txt',
 'Leon.txt',
 'LLeida.txt',
 'LogroÃ±o.txt',
 'Lugo.txt',
 'Madrid.txt',
 'Malaga.txt',
 'Marbella.txt',
 'Mataro.txt',
 'Melilla.txt',
 'Mostoles.txt',
 'Murcia.txt',
 'Ourense.txt',
 'Oviedo.txt',
 'Palencia.txt',
 'Palma.txt',
 'Parla.txt',
 'Pontevedra.txt',
 'Sabadell.txt',
 'Salamanca.txt',
 'San Cristobal.txt',
 'Santa Coloma.txt',
 'Santa Cruz.txt',
 'Santander.txt',
 'Segovia.txt',
 'Sevilla.txt',
 'Soria.txt',
 'Terragona.txt',
 'Terrasa.txt',
 'Teruel.txt',
 'Toledo.txt',
 'Torrejon.txt',
 'Valencia.txt',
 'Valladolid.txt',
 'Vigo.txt',
 'Zamora.txt',
 'Zaragoza.txt']

### La siguiente funcion lee las métricas de forma cada documento y las junta en un nuevo dataframe.
### Los argumentos son:

 1.- Files: Un diccionario con el nombre de los archivos.

 2.- n = El número de lineas desde la parte final del documento donde se encuentran las metricas.
 
 3.- metricas = El nombre de las métricas que forman las columnas del nuevo dataset.

In [19]:
def crear_df_metricas(files,n, metricas):
    dict_metricas = {}
    df_metricas = pd.DataFrame(columns= metricas)
    for file in files:
        n = n
        with open(file) as f:
            lines = f.readlines()[n:]
            for line in lines:
                x = line.split(" ", 1)
                dict_metricas[x[0]] = x[1][:-1]                 
                df_temp = pd.DataFrame(dict_metricas, index = [file])
            df_metricas = pd.concat([df_metricas,df_temp], axis = 0)   
    
    return df_metricas

In [20]:
metricas = ['PAFRAC', 'SHAPE_MN', 'SHAPE_MD', 'PARA_MN', 'PARA_MD', 'FRAC_MN', 'FRAC_MD', 'SQUARE_MN', 'SQUARE_MD']

In [21]:
ciudades_forma = crear_df_metricas(archivos_forma,-9,metricas)

In [23]:
ciudades_forma

,PAFRAC,SHAPE_MN,SHAPE_MD,PARA_MN,PARA_MD,FRAC_MN,FRAC_MD,SQUARE_MN,SQUARE_MD,Landscape
Albacete.txt,1.036782,1.239875,1.196013,0.251356,0.242674,1.071821,1.061970,0.523948,0.500157,NaN
Alcala.txt,1.025171,1.293679,1.267219,0.325155,0.328765,1.095561,1.092224,0.575723,0.578704,NaN
Alconbendas.txt,1.028039,1.247419,1.185695,0.205145,0.164615,1.066683,1.054622,-3.814456,0.493816,NaN
Alcorcon.txt,1.029029,1.248374,1.223028,0.262249,0.250720,1.068275,1.070708,0.539567,0.536001,NaN
Algeciras.txt,1.048912,1.259996,1.214451,0.404055,0.386923,1.091095,1.080717,0.539164,0.521263,NaN
...,...,...,...,...,...,...,...,...,...,...
Valencia.txt,1.042692,1.257228,1.213188,0.306693,0.276416,1.079785,1.070835,0.545070,0.525500,Indices
Valladolid.txt,1.029885,1.260936,1.224576,0.297016,0.258540,2.406995,1.072220,0.554657,0.537779,Indices
Vigo.txt,1.109125,1.296248,1.232625,0.278694,0.239418,1.086155,1.074478,0.565968,0.551518,Indices
Zamora.txt,1.047176,1.260158,1.217223,0.350769,0.330062,1.086805,1.076438,0.547378,0.528852,Indices
Zaragoza.txt,1.045270,1.245742,1.197868,0.269641,0.255703,1.074214,1.064998,0.036638,0.504216,Indices

In [25]:
ciudades_forma_drop = ciudades_forma.drop("Landscape", axis = 1)

In [26]:
ciudades_forma_drop

,PAFRAC,SHAPE_MN,SHAPE_MD,PARA_MN,PARA_MD,FRAC_MN,FRAC_MD,SQUARE_MN,SQUARE_MD
Albacete.txt,1.036782,1.239875,1.196013,0.251356,0.242674,1.071821,1.061970,0.523948,0.500157
Alcala.txt,1.025171,1.293679,1.267219,0.325155,0.328765,1.095561,1.092224,0.575723,0.578704
Alconbendas.txt,1.028039,1.247419,1.185695,0.205145,0.164615,1.066683,1.054622,-3.814456,0.493816
Alcorcon.txt,1.029029,1.248374,1.223028,0.262249,0.250720,1.068275,1.070708,0.539567,0.536001
Algeciras.txt,1.048912,1.259996,1.214451,0.404055,0.386923,1.091095,1.080717,0.539164,0.521263
...,...,...,...,...,...,...,...,...,...
Valencia.txt,1.042692,1.257228,1.213188,0.306693,0.276416,1.079785,1.070835,0.545070,0.525500
Valladolid.txt,1.029885,1.260936,1.224576,0.297016,0.258540,2.406995,1.072220,0.554657,0.537779
Vigo.txt,1.109125,1.296248,1.232625,0.278694,0.239418,1.086155,1.074478,0.565968,0.551518
Zamora.txt,1.047176,1.260158,1.217223,0.350769,0.330062,1.086805,1.076438,0.547378,0.528852
Zaragoza.txt,1.045270,1.245742,1.197868,0.269641,0.255703,1.074214,1.064998,0.036638,0.504216

In [54]:
#ciudades_forma_drop.to_csv(r"C:/projectos/manifolds/ciudades/datos/metricas/metricas_forma.csv")

In [33]:
ciudades_forma_drop.to_csv(r"C:\Users\CRISTIAN\github\clustering-metrics\datos\metricas\ciudades_forma.csv", encoding='ISO-8859-1')

THE END