In [1]:
import pandas as pd
import geopandas as gpd
import os
import glob
import string

In [2]:
path =(r"C:/projectos/shapes/marcos_clasificacion/")
# Change the directory
os.chdir(path)

In [3]:
dict_shapes = {}

# Iterate over all the files in the directory
for file in os.listdir():
   if file.endswith('.shp') and file[0].isalpha():
       temp = gpd.read_file(file)
       dict_shapes[file] = temp

KeyboardInterrupt:

In [8]:
dict_shapes["Albacete_class.shp"].head(2)

,AREA,REFCAT,A_TOT_EDIF,SUP_ED_0,SUP_ED_1,MAX_PLANTA,NUM_INM_R,USO,PROP_AE_AT,RES_UNI,...,IND,OFI,COM,EQUIP_SANI,EQUIP_EDU,EQUIP_OTR,OCIO_ESP,HOS_REST,ED_SING,geometry
0,472,6978915WJ9167H,0,0,0,0,0,SIN_EDIF,0.000000,0,...,0,0,0,0,0,0,0,0,0,"POLYGON ((596928.841 4317779.775, 596895.924 4..."
1,2138,6879902WJ9167H,5918,939,1177,4,29,RES_PLU,0.550514,0,...,0,0,0,0,0,1,0,0,0,"POLYGON ((596875.544 4317938.072, 596849.645 4..."

In [10]:
clases_agregadas = pd.read_csv("C:/projectos/shapes/clases_agregadas.csv")
clases_agregadas

           USO    USO_AG
0          COM       COM
1      ED_SING   ED_SING
2    EQUIP_EDU     EQUIP
3    EQUIP_OTR     EQUIP
4   EQUIP_SANI     EQUIP
5     HOS_REST  HOS_REST
6          IND       IND
7       IND_MX       IND
8      OCIO_ES      OCIO
9          OFI       OFI
10     RES_PLU   RES_PLU
11  RES_PLU_MX   RES_PLU
12     RES_UNI   RES_UNI
13  RES_UNI_MX   RES_UNI
14    SIN_EDIF  SIN_EDIF

In [12]:
def uso_agregado_gtp(data_in, clases):
    data_out = {}
    for key, value in data_in.items():
        data_out[key] = value.merge(clases, on = 'USO', how = 'left')
    return data_out

In [13]:
def uso_agregado(data_in,data_out,clases):
    for keys, values in data_in.items():
        data_out[keys]= pd.merge(data_in[keys], clases, on ='USO', how = "left")
    return(data_out)

In [14]:
uso_agregado_gtp = uso_agregado_gtp(dict_shapes,clases_agregadas)

In [18]:
uso_agregado_gtp["Albacete_class.shp"].head(2)

,AREA,REFCAT,A_TOT_EDIF,SUP_ED_0,SUP_ED_1,MAX_PLANTA,NUM_INM_R,USO,PROP_AE_AT,RES_UNI,...,OFI,COM,EQUIP_SANI,EQUIP_EDU,EQUIP_OTR,OCIO_ESP,HOS_REST,ED_SING,geometry,USO_AG
0,472,6978915WJ9167H,0,0,0,0,0,SIN_EDIF,0.000000,0,...,0,0,0,0,0,0,0,0,"POLYGON ((596928.841 4317779.775, 596895.924 4...",SIN_EDIF
1,2138,6879902WJ9167H,5918,939,1177,4,29,RES_PLU,0.550514,0,...,0,0,0,0,1,0,0,0,"POLYGON ((596875.544 4317938.072, 596849.645 4...",RES_PLU

In [20]:
## Crea un código único para los usos agregados

import numpy as np
import pandas as pd

def asignacion_codigo_categorias_chatgtp(data_in):
    data_out = {}
    for key, df in data_in.items():
        df = df.reset_index()
        usos = df['USO_AG'].unique()
        cod_usos = np.arange(len(usos))
        cod_map = pd.Series(cod_usos, index=usos)
        df['cod_usos_ag'] = df['USO_AG'].map(cod_map)
        data_out[key] = df
    return data_out

In [21]:
asignacion_usos_agregados = asignacion_codigo_categorias_chatgtp(uso_agregado_gtp)

In [24]:
asignacion_usos_agregados["Albacete_class.shp"].head(2)

,index,AREA,REFCAT,A_TOT_EDIF,SUP_ED_0,SUP_ED_1,MAX_PLANTA,NUM_INM_R,USO,PROP_AE_AT,...,COM,EQUIP_SANI,EQUIP_EDU,EQUIP_OTR,OCIO_ESP,HOS_REST,ED_SING,geometry,USO_AG,cod_usos_ag
0,0,472,6978915WJ9167H,0,0,0,0,0,SIN_EDIF,0.000000,...,0,0,0,0,0,0,0,"POLYGON ((596928.841 4317779.775, 596895.924 4...",SIN_EDIF,0
1,1,2138,6879902WJ9167H,5918,939,1177,4,29,RES_PLU,0.550514,...,0,0,0,1,0,0,0,"POLYGON ((596875.544 4317938.072, 596849.645 4...",RES_PLU,1

In [39]:
asignacion_usos_agregados["Albacete_class.shp"][asignacion_usos_agregados["Albacete_class.shp"].loc[:,"USO_AG"] == 'nan']

Empty GeoDataFrame
Columns: [index, AREA, REFCAT, A_TOT_EDIF, SUP_ED_0, SUP_ED_1, MAX_PLANTA, NUM_INM_R, USO, PROP_AE_AT, RES_UNI, RES_PLU, IND, OFI, COM, EQUIP_SANI, EQUIP_EDU, EQUIP_OTR, OCIO_ESP, HOS_REST, ED_SING, geometry, USO_AG, cod_usos_ag]
Index: []

[0 rows x 24 columns]

In [40]:
for keys, values in asignacion_usos_agregados.items():
    asignacion_usos_agregados[keys].to_file('C:/projectos/shapes/asignacion_ag/'+ keys)